package pl.edu.pw.mini.cadcam.pusn.controller;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jogamp.opengl.awt.GLJPanel;
import org.jdesktop.swingx.JXPanel;

import javax.swing.*;
import java.awt.*;

public class MainController {
    private JPanel mainPane;
    private GLJPanel glPane;
    private JSplitPane splitPane;
    private JScrollPane controlsPane;

    public MainController() {
        $$$setupUI$$$();

        splitPane.setDividerLocation(0.75);

        JXPanel panel = new JXPanel(new BorderLayout());
        controlsPane.setViewportView(panel);
        panel.setScrollableTracksViewportWidth(true);
        panel.setScrollableTracksViewportHeight(false);

        GLController glController = new GLController(glPane);

        InterpolationController interpolationController = new InterpolationController(glController::setAnimation);
        panel.add(interpolationController.getMainPane(), BorderLayout.CENTER);

    }

    public Container getMainPane() {
        return mainPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        splitPane = new JSplitPane();
        splitPane.setDividerLocation(0);
        splitPane.setDividerSize(15);
        splitPane.setOneTouchExpandable(true);
        splitPane.setResizeWeight(0.75);
        mainPane.add(splitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        glPane = new GLJPanel();
        splitPane.setLeftComponent(glPane);
        controlsPane = new JScrollPane();
        splitPane.setRightComponent(controlsPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

}
